"""create prices table

Revision ID: fc541833ebc1
Revises:
Create Date: 2026-01-22 21:18:39.571062

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc541833ebc1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("ts", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prices_ticker"), "prices", ["ticker"], unique=False)
    op.create_index(op.f("ix_prices_ts"), "prices", ["ts"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prices_ts"), table_name="prices")
    op.drop_index(op.f("ix_prices_ticker"), table_name="prices")
    op.drop_table("prices")
    # ### end Alembic commands ###
